# Generated by Django 3.2.6 on 2022-07-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0005_exam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['-date', '-time_start']},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-date', '-time_start']},
        ),
        migrations.AlterField(
            model_name='class',
            name='time_end',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='class',
            name='time_start',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='exam',
            name='time_end',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='exam',
            name='time_start',
            field=models.TextField(max_length=10),
        ),
    ]
