# Generated by Django 3.2.6 on 2022-07-17 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0006_auto_20220717_1952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['date', 'time_start']},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['date', 'time_start']},
        ),
    ]
