# Generated by Django 3.2.6 on 2022-07-17 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='status',
        ),
    ]
