# Generated by Django 3.2.6 on 2022-07-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_remove_notes_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('accept', 'accept'), ('reject', 'reject')], default='pending', max_length=15),
        ),
    ]
