# Generated by Django 3.2.6 on 2022-07-17 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_notes_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
